[build]
  Functions = "functions"
  command = "yarn run build"
  publish = "dist"
  environment = { NODE_VERSION = "8.9.0" }


[[redirects]]
  from = "/index.html"
  to = "https://jbzy2tech.blogspot.com/"
  status = 301

